### PR TITLE
Date and Time fields when creating event, Task character limit and front-end cleanup, Cancel button Create Event Page

### PR DESCRIPTION
**Pull request by jnielsen713**
This pull request should close out 3 issues.
-The create event page now has actual date and time fields allowing for more streamlined data
-Tasks now have a limit of 30 characters and should not be cut off on the create event page
-The cancel button on the create event page should now work

### CODE REVIEW

**Review by IsaaMaster — APPROVED** [review]
Looks good! Thanks for all your hard work!

**Comment by Brycyn** [comment]
It looks good and the fields are really clean, but I am getting an error after creating the event. Please let me know if anyone else is getting this error

Screenshot 2023-11-25 113507

**Review by alpetee — CHANGES_REQUESTED** [review]
I'm getting the same error as Brycyn. I'm not sure where exactly this error would be, but it looks like line 9 of the javascript file is where you work with the user_id.

**Comment by jnielsen713** [comment]
I can't seem to recreate the error. Generally errors thrown for lack of a default value means you have data in the database that predates the user_id column existing, did you try flushing?

**Review by magictwicks — APPROVED** [review]
no error on my end... maybe we talk in person?

**Pull request merged**
