### PR TITLE
Handle create event

### PR DESCRIPTION
**Pull request by jnielsen713**
Description: This pull request covers our issue #10 by modifying the view for the create event page to handle POST data, using it to build an event and save that event to the database. This pull request also slightly modifies the event model everywhere it is used to allow functionality of the host and description instance variables.

### CODE REVIEW

**Review by IsaaMaster — CHANGES_REQUESTED** [review]
Everything looks good codewise, just make sure to add comments and document what the class "CreateEventForm2" is and also use comments to describe what is going on in "def createEvent' in views.py. I know it's probably pretty straightforward, but it's important to just document everything (especially for larger projects) so we are all on the same page.

**Review by Brycyn — APPROVED** [review]
Other than the changes Isaac requested, the code worked well when tested.

**Comment by jnielsen713** [comment]
Sweet, I'll add the comments in a bit, not planning on modifying code though, if its good!

**Review by IsaaMaster — APPROVED** [review]
Ok, those comments look good and all the code looks good too. Thanks!

**Review by alpetee — APPROVED** [review]

**Pull request merged**
