### PR TITLE
Tasks Sign Up front and backend functionality, task display

### PR DESCRIPTION
**Pull request by IsaaMaster**
Added the following features:
           - Added task sign-up as part of event RSVP. Now, when you sign up for a task in the RSVPing process, the task will be 
             marked as completed and saved as part of your RSVP. As a result, it will not longer be shown in the options for 
             available tasks. 
           - Displayed who's doing what task for the event on the event detail page. 
           
          

Note: Since we could not get the Django Form to work, this has instead been implemented with a HTML form and simply parsing and handling the POST data within the EventDetail View itself.

### CODE REVIEW

**Review by alpetee — APPROVED** [review]

**Comment by jnielsen713** [comment]
I get an error when I try to migrate:
`MySQLdb.OperationalError: (1054, "Unknown column 'planner_task.completed' in 'field list'")`
Probably something on my end but I can't try this out until I can successfully migrate

**Comment by IsaaMaster** [comment]
> I get an error when I try to migrate:
> 
> MySQLdb.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`eventplanner`.`#sql-alter-39d-c`, CONSTRAINT `planner_rsvp_task_id_9af8ee55_fk_planner_task_id` FOREIGN KEY (`task_id`) REFERENCES `planner_task` (`id`))'))
> 
> Probably something on my end but I can't try this out until I can successfully migrate

You might have to do Python manage.py flush, which resets your database. Then you should be able to make migrations.

**Review by Brycyn — APPROVED** [review]
The code looks and  works great, easy to use!

**Review by jnielsen713 — APPROVED** [review]
This works perfectly, and looks good too! :D

**Pull request merged**
