### PR TITLE
Login/Signup functionality

### PR DESCRIPTION
**Pull request by IsaaMaster**
See linked issue for details

### CODE REVIEW

**Review by alpetee — COMMENTED** [review]
When I click on the "Sign up" button, I get this error: 
"The view planner.views.signup didn't return an HttpResponse object. It returned None instead" 

When I click on the "Log in" button, I get the error: 
"Invalid block tag on line 68: 'endblock'. Did you forget to register or load this tag?" 

Are these working on your machine? I migrated just incase I was missing something necessary to run on mine but it didn't change anything.

**Comment by alpetee** [comment]
> When I click on the "Sign up" button, I get this error: "The view planner.views.signup didn't return an HttpResponse object. It returned None instead"
> 
> When I click on the "Log in" button, I get the error: "Invalid block tag on line 68: 'endblock'. Did you forget to register or load this tag?"
> 
> Are these working on your machine? I migrated just incase I was missing something necessary to run on mine but it didn't change anything.

I just ran it on main instead of your branch and it's working... not sure what happened there haha. Looks great with the Logo!

**Comment by IsaaMaster** [comment]
> When I click on the "Sign up" button, I get this error: "The view planner.views.signup didn't return an HttpResponse object. It returned None instead"
> 
> When I click on the "Log in" button, I get the error: "Invalid block tag on line 68: 'endblock'. Did you forget to register or load this tag?"
> 
> Are these working on your machine? I migrated just incase I was missing something necessary to run on mine but it didn't change anything.

I fixed these changes which were actually on my branch. It was just some stuff that accidentally got deleted when there was a merge conflict.

**Review by jnielsen713 — APPROVED** [review]
Tried it out and it works great!

**Review by alpetee — APPROVED** [review]
Looks good

**Pull request merged**
