### PR TITLE
Added username, and manage account page

### PR DESCRIPTION
**Pull request by magictwicks**
This pull request: 
- requires a separate username and email field for accounts
- adds first and last name fields in sign up
- displays your name on the navbar
- created manage account page
- allows user to change their username at any time 
- fixed merge conflicts
- rounded input fields

### CODE REVIEW

**Review by IsaaMaster — APPROVED** [review]
Looks good1

**Review by alpetee — COMMENTED** [review]
The manage account button and form work great! 
When I log out and try to sign in or log in I get an error-- do you mean to have a space in the quotes on line 110? 
<p><a href="{% url " loginPage" %}">Already have an account?</a></p>
vs 
<p><a href="{% url "loginPage" %}">Already have an account?</a></p>

Maybe this is the issue?

**Review by Brycyn — DISMISSED** [review]
When I logout and try to log back in , I get an error: I believe its the same error Allie was getting. 

Screenshot 2023-11-18 195949

**Review by alpetee — APPROVED** [review]
Wonderful! Runs great on my end.

**Review by IsaaMaster — APPROVED** [review]
LGTM!

**Pull request merged**
