### PR TITLE
Tying the User  who made the event to the event(User email)-Backend

### PR DESCRIPTION
**Pull request by Brycyn**
When an event is created, it is tied to the person that creates it. I tested this by having the "user" object render in the html and it returned my email. once I saw that it worked I removed it from the EvenDetails.hmtl. I was not sure how we would want to implement this.

### CODE REVIEW

**Review by alpetee — CHANGES_REQUESTED** [review]
Backend all looks good-- as far as when to implement, I think linking the user to who its "brought to you by" now is a good idea! It also brings into question if we should ask the user who is hosting the event or if the user who creates it is automatically linked without question (which I think is fine for now and what the client seems to want).

**Review by IsaaMaster — APPROVED** [review]
Looks good to me!

**Comment by Brycyn** [comment]
Changes made! user can now see which accounts created the event
Screenshot 2023-11-19 201805
Screenshot 2023-11-19 204841
Screenshot 2023-11-19 204851

**Review by magictwicks — APPROVED** [review]
Looks good to me

**Review by IsaaMaster — APPROVED** [review]
Looks good!

**Pull request merged**
