### PR TITLE
Cleaning grid

### PR DESCRIPTION
**Pull request by alpetee**
Text is limited now inside of the fixed box. Some things I would love feedback on: 
  I want the amount of lines displayed for event description to be dependent on the amount of lines that are displayed for the title (so if the title takes up 2 lines, the event details would only take up 1. But if the title only takes up one line, the event details can take up 2 lines). Right now it is dependent on the amount of characters in the title which does the job but isn't as consistent as I like. 
  I also am thinking about if we were to give every title 2 lines of space so the spacing would be the same on every event. Let me know what you think!

### CODE REVIEW

**Review by IsaaMaster — CHANGES_REQUESTED** [review]
Make to sure to have everything in the <style> element in our CSS file instead. In general its just a good practice to have all HTML in one file and CSS in another.

**Review by Brycyn — APPROVED** [review]
The code looks good, I tested it and it is functional as well. 

potential feature :
summary text for the description (Short title to display on card  for longer event names).
might be unnecessary, but may look clean.

**Comment by alpetee** [comment]
> Make to sure to have everything in the <style> element in our CSS file instead. In general its just a good practice to have all HTML in one file and CSS in another.

Recent commit has these changes!

**Review by IsaaMaster — APPROVED** [review]
Looks good to me! Great Job!

**Pull request merged**
