### PR TITLE
Sprint4 tc

### PR DESCRIPTION
**Pull request by IsaaMaster**
View test cases here: **https://docs.google.com/spreadsheets/d/15zdkhmZ9gnWaLH_iCZf4ifWMGybpuCN09YdPO_DJcNI/edit#gid=444844600**

Note: some of the test cases will fail, because Josh's pull request hasn't been brought in yet, but they should pass once that has been done.

### CODE REVIEW

**Review by magictwicks — DISMISSED** [review]
Looks good!

**Review by alpetee — DISMISSED** [review]
Yay! Passing!

**Review by magictwicks — APPROVED** [review]
yeehaw

**Review by jnielsen713 — APPROVED** [review]
Sweeeeet

**Pull request merged**
